// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrQCnKMEw54qgklm0kCyLogzjmx18Z1U',
    appId: '1:980697009125:web:7f7bd5e93176433c8f3d0c',
    messagingSenderId: '980697009125',
    projectId: 'e-commerce-282a6',
    authDomain: 'e-commerce-282a6.firebaseapp.com',
    storageBucket: 'e-commerce-282a6.firebasestorage.app',
    measurementId: 'G-G4XRMWEQCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOQw0Xq0RiKhP4VkuT9uHdxBUNttYkaA',
    appId: '1:980697009125:android:d04112a423ef07c48f3d0c',
    messagingSenderId: '980697009125',
    projectId: 'e-commerce-282a6',
    storageBucket: 'e-commerce-282a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtTLTIHmXbe_-iqO9q14TjcLog04YnrPg',
    appId: '1:980697009125:ios:444ce6d81c3fc6468f3d0c',
    messagingSenderId: '980697009125',
    projectId: 'e-commerce-282a6',
    storageBucket: 'e-commerce-282a6.firebasestorage.app',
    iosBundleId: 'com.yasmen.boost.boo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtTLTIHmXbe_-iqO9q14TjcLog04YnrPg',
    appId: '1:980697009125:ios:444ce6d81c3fc6468f3d0c',
    messagingSenderId: '980697009125',
    projectId: 'e-commerce-282a6',
    storageBucket: 'e-commerce-282a6.firebasestorage.app',
    iosBundleId: 'com.yasmen.boost.boo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlrQCnKMEw54qgklm0kCyLogzjmx18Z1U',
    appId: '1:980697009125:web:229ddf4ee0a7ead68f3d0c',
    messagingSenderId: '980697009125',
    projectId: 'e-commerce-282a6',
    authDomain: 'e-commerce-282a6.firebaseapp.com',
    storageBucket: 'e-commerce-282a6.firebasestorage.app',
    measurementId: 'G-03PE1GLYVF',
  );
}
